version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8000:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            backend:
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root 
        volumes:
            # - ./dump:/docker-entrypoint-initdb.d
            # - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            backend:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8001:80
        restart: always
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root 
        networks:
            backend:
volumes:
    persistent:
networks:
    backend: